#!/usr/bin/env python3
"""Convert SVG files in res/ to BinaryData.cpp hex arrays."""
import os, glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RES_DIR = os.path.join(SCRIPT_DIR, "res")
OUTPUT = os.path.join(SCRIPT_DIR, "Source", "BinaryData.cpp")

# Get SVG files, put the two we use first
svg_files = []
for name in ["PlateauPanelDark.svg", "PlateauPanelLight.svg"]:
    path = os.path.join(RES_DIR, name)
    if os.path.exists(path):
        svg_files.append(path)

def to_c_array(data):
    """Convert bytes to C hex array."""
    parts = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        parts.append(f"    {hex_vals},")
    return "\n".join(parts)

header = """// Auto-generated by generate_binary.py
#include "BinaryData.h"

namespace BinaryData {

"""

footer = """

} // namespace BinaryData
"""

entries = []
for path in svg_files:
    name = os.path.basename(path).replace(".", "_")
    size = os.path.getsize(path)
    with open(path, "rb") as f:
        data = f.read()
    arr = to_c_array(data)
    entries.append(f"const char {name}[] = {{\n{arr}\n}};\n")
    entries.append(f"const int {name}Size = {size};\n")

with open(OUTPUT, "w") as f:
    f.write(header)
    f.write("\n".join(entries))
    f.write(footer)

print(f"Generated {OUTPUT}")
for e in entries:
    print(e.strip())
